### ISSUE TITLE
fuzzy match: substitution count not as expected

### ISSUE THREAD

**Issue by mrabarnett** [mrabarnett/mrab-regex#155]
**[Original report](https://bitbucket.org/mrabarnett/mrab-regex/issue/155) by Colin Anthony (Bitbucket: [ColinAnthony](https://bitbucket.org/ColinAnthony), GitHub: [ColinAnthony](https://github.com/ColinAnthony)).**

----------------------------------------

I have encountered a behaviour in the fuzzy matching (bestmatch or enhancedmatch) option that I cannot understand.
I outlined the problem on stackexchange: http://stackoverflow.com/questions/31193749/python-regex-module-fuzzy-match-substitution-count-not-as-expected
but got no replies.

The issue is outlined below:

You can specify the allowable number of substitutions,s, insertions,i, deletions,d, and total errors,e, allowed

The fuzzy_counts 'option' returns a tuple (0,0,0), where: 
match.fuzzy_counts[0] = the counts for 's', 
match.fuzzy_counts[1] = counts for 'i' and 
match.fuzzy_counts[2] = counts for 'd'
The deletions and insertions are counted as expected, but not the substitutions

In the example below, the only change is a single character deleted in the query, yet the substitutions count is 6 (7 if the BESTMATCH option is removed)

How are the substitutions counted?

I would be grateful of someone can anyone explain how this works to me

import regex

reference = "(TATGGGA[CT][GC]AAAG[CT]CT[AC]AA[GA]CCATGTG){s<7,i<3,d<3,e<8}"

query = "TATGGACCAAAGTCTCAAGCCATGTG" 

match = regex.search(reference, query, regex.BESTMATCH)

print(match.fuzzy_counts)

(6,0,1)

Reducing the s to s < 3 changes the fuzzy match tuple score downwards:

reference = "(TATGGGA[CT][GC]AAAG[CT]CT[AC]AA[GA]CCATGTG){s<3,i<3,d<3,e<4}" 

query = "TATGGACCAAAGTCTCAAGCCATGTG"  

match = regex.search(reference, query, regex.BESTMATCH)

print(match.fuzzy_counts) 

(1,0,1)

reducing the allowed error for 's' even further returns the expected 's' score for this match:

reference = "(TATGGGA[CT][GC]AAAG[CT]CT[AC]AA[GA]CCATGTG){s<2,i<3,d<3,e<4}"

query = "TATGGACCAAAGTCTCAAGCCATGTG" 

match = regex.search(reference, query, regex.BESTMATCH)

print(match.fuzzy_counts)

(0,0,1)

I want to use the substitution, insertion and deletion scores to plot the distance of each match from the reference, but need to understand how the scoring works, or if the above behaviour is a bug.

(python 64bit, version 2.7.9 -ubuntu 15.04)

**Comment by contestq** [comment]
Can ins del  sub be set to different costs ？
