### ISSUE TITLE
PEP 561 Compliance?

### ISSUE THREAD

**Issue by sinhalaquiz** [mrabarnett/mrab-regex#436]
Hi,

I'm trying to import the regex library to another project and am getting errors due to Missing type hints.

https://github.com/kantord/LibreLingo/pull/1752#issuecomment-956659787

I'm only beginning to learn about these things so my question might be super dumb :-) .

Does regex distribute the type info? Do you have any plans to do so?

**Comment by mrabarnett** [comment]
There are no type hints. They were introduced only in Python 3.5, and they aren't required. I have no plans to add them.
