### ISSUE TITLE
is there any docs for this package?

### ISSUE THREAD

**Issue by sunM123** [mrabarnett/mrab-regex#438]
As title, I want to read how the API of this library is used，and I did not find any documents for this package

**Comment by 5j9** [comment]
As the [README.rst](https://github.com/mrabarnett/mrab-regex/blob/hg/README.rst) file states, the API "is backwards-compatible with the [standard 're' module](https://docs.python.org/3/library/re.html), but offers additional functionality." Those additions are mostly covered in the README.rst.

**Comment by mrabarnett** [comment]
There are no additional docs.
