### ISSUE TITLE
Readability and editability of long sets 

### ISSUE THREAD

**Issue by dlukes** [mrabarnett/mrab-regex#441]
Sets can grow large, which can make them hard to read and edit:

```python
import regex as re

def test(pat):
    # pat should only match . → True, False, False
    for s in ". \n":
        print(bool(pat.match(s)))

pat = re.compile(r"""[.;:?!'"\N{ACUTE ACCENT}\N{MODIFIER LETTER TURNED COMMA}\N{GREEK PSILI}\N{MODIFIER LETTER APOSTROPHE}\N{MODIFIER LETTER REVERSED COMMA}]""")
test(pat)  # True, False, False
```

Normally, that's when I'd reach for `re.VERBOSE`, but unfortunately, inside sets, whitespace always counts, so the following set includes `" "` and `"\n"`:

```python
pat = re.compile(
    r"""
    [.;:?!'"
     \N{ACUTE ACCENT}
     \N{MODIFIER LETTER TURNED COMMA}
     \N{GREEK PSILI}
     \N{MODIFIER LETTER APOSTROPHE}
     \N{MODIFIER LETTER REVERSED COMMA}
    ]
    """,
    flags=re.VERBOSE,
)
test(pat)  # ! True, True, True !
```

Would it be possible to implement an alternative verbose flag which ignores (literal) whitespace everywhere, even inside sets?

**Comment by dlukes** [comment]
I can of course think of workarounds, but in my mind, they seem to hurt both readability and reliability. It's not "just a regex" anymore, there are additional points of failure.

---

For instance, I can get rid of the whitespace myself (but then I have to remember it's not a true `re.VERBOSE` regex and I can't add comments):

```python
# pat.pattern is the second pattern in the previous coment
# -- the one that didn't work with re.VERBOSE
pat = re.compile("".join(l.strip() for l in pat.pattern.splitlines()))
test(pat)  # True, False, False
```

---

Or I can rely on the concatenation of adjacent string literals:

```python
pat = re.compile(
    '''[.;:?!'"'''
    r"\N{ACUTE ACCENT}"
    r"\N{MODIFIER LETTER TURNED COMMA}"
    r"\N{GREEK PSILI}"
    r"\N{MODIFIER LETTER APOSTROPHE}"
    r"\N{MODIFIER LETTER REVERSED COMMA}"
    "]",
    flags=re.VERBOSE,
)
test(pat)  # True, False, False
```

---

Or I can define the set as a Python list and build it myself:

```python
my_set = list('''.;:?!'"''') + [
    r"\N{ACUTE ACCENT}",
    r"\N{MODIFIER LETTER TURNED COMMA}",
    r"\N{GREEK PSILI}",
    r"\N{MODIFIER LETTER APOSTROPHE}",
    r"\N{MODIFIER LETTER REVERSED COMMA}",
]
pat = re.compile("[" + "".join(my_set) + "]")
test(pat)  # True, False, False
```

---

Or I can use a named list:

```python
pat = re.compile(r"\L<my_set>", my_set=my_set)
test(pat)  # True, False, False
```

---

If you'd rather not implement an alternative verbose flag, would you particularly recommend against any of these workarounds? It feels like the named list might have performance implications, because the engine might be able to optimize the matching of sets (as in `[abc]`) in ways that alternations (as in `a|b|c`) can't be (unless it's smart enough to figure out when an alternation is equivalent to a set?), but that's just a wild guess, I know nothing about the codebase.

**Comment by mrabarnett** [comment]
Named lists are optimised to character sets wherever possible, so that's what I'd recommend.

**Comment by dlukes** [comment]
Understood, thank you!
