### ISSUE TITLE
Fuzzy regex matching doesn't seem to test insertions correctly

### ISSUE THREAD

**Issue by fathom-parth** [mrabarnett/mrab-regex#442]
If I have the following regex:
```
(?\bha\b){i:[ ])
```
which is "ha" only allowing space insertions with word boundaries around "ha" -- it matches against:
```
having
```

When I look at the fuzzy counts, it says the regex added 4 insertions to match against "having" which are presumably "ving" but my regex should only allow inserting spaces.

Code snippet for replication:
```
text = "having"

pattern = re.compile(r"(?:\bha\b){i:[ ]}", re.I)

pattern.search(text)
```

Additionally, I'm using version 2020.11.13

Lastly, I think fuzzy match testing against character literals are broken: https://github.com/mrabarnett/mrab-regex/commit/d6ba23d2eb9af72432c2e43b68413b5ff8b55971#r59740789 (probably a separate issue to file)

**Comment by mrabarnett** [comment]
Fixed in regex 2021.11.9.
