### ISSUE TITLE
Can't install in Alpine (no musllinux wheel)

### ISSUE THREAD

**Issue by ghost** [mrabarnett/mrab-regex#446]
If I `docker run -ti python:3.10-alpine /bin/sh`, I can't `pip install regex`. It wants to compile. Which, I could give it a compiler, but it'd be nice to be able to install a musllinux wheel.

`regex` is so prolific that I think this keeps a lot of people from using `-alpine` Python Docker images.

What would it take to have a musllinux wheel?

**Comment by ghost** [comment]
Remove this line to build `musl` wheels:
`CIBW_SKIP: "*musllinux*"`

No need to release a new version, the existing wheels will be skipped when uploading to PyPI.

**Comment by mrabarnett** [comment]
It took almost 40 minutes on the second attempt, but the musllinux wheels are now on PyPI.

**Comment by ghost** [comment]
Awesome!! Thank you so much!!

**Comment by ghost** [comment]
> It took almost 40 minutes on the second attempt

This splits to manylinux/musllinux.
I tested with my module, it builds manylinux/musllinux wheels in parallel.
```diff
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -102,9 +102,11 @@ jobs:
     strategy:
       matrix:
         arch: [aarch64, ppc64le, s390x]
+        skip_image: ["*musllinux*", "*manylinux*"]
 
     env:
       CIBW_ARCHS: ${{ matrix.arch }}
+      CIBW_SKIP:  ${{ matrix.skip_image }}
 
     steps:
       - uses: actions/checkout@v2
```

**Comment by mrabarnett** [comment]
Thanks for that. I've committed it locally ready for the next release, whenever that is.
