### ISSUE TITLE
Missing git version tags

### ISSUE THREAD

**Issue by kloczek** [mrabarnett/mrab-regex#447]
Is it possible to add at lease last version tag `2021.11.10`?

**Comment by mrabarnett** [comment]
I'll starting adding a version tag. I don't think I can add one to what's on GitHub without triggering a build and release.

**Comment by ghost** [comment]
> I'll starting adding a version tag. I don't think I can add one to what's on GitHub without triggering a build and release.

You can tag them locally, and push the tags with the next release.

In addition, please consider using two branches, a `dev` branch and a `release` branch.
Wheels are built and published to pypi only when the `release` branch is pushed. If want to publish a new version, just merge `dev` branch to `release` branch, and push to GitHub  repository.

I'm using this mode:
https://github.com/animalize/pyzstd/blob/dev/.github/workflows/main.yml

**Comment by kloczek** [comment]
No .. tagging does not trigger actions.

**Comment by kloczek** [comment]
Really please add of at least last version ..

**Comment by mrabarnett** [comment]
That's strange. The recent versions are tagged locally, and I assumed that when I pushed to GitHub they would be pushed too. Looks like they weren't.

**Comment by mrabarnett** [comment]
OK, fixed.

**Comment by kloczek** [comment]
Thank you 👍 
Closing.
