### ISSUE TITLE
 unicode fail

### ISSUE THREAD

**Issue by p-i-** [mrabarnett/mrab-regex#451]
`regex` is failing to process certain strings containing unicode characters.
`re` has no trouble with the same strings.

```
In [1]: import re

In [2]: re.findall(r"\w.*?(\w)", "a ⬆️ b")
Out[2]: ['b']

In [3]: re.findall(r"\d.*?(\d)", "1 ⬆️ 2")
Out[3]: ['2']

In [4]: %pip install regex
:

In [5]: import regex

In [6]: regex.findall(r"\w.*?(\w)", "a ⬆️ b")
Out[6]: ['️']

In [7]: regex.findall(r"\d.*?(\d)", "1 ⬆️ 2")
Out[7]: ['2']
```

**Comment by mrabarnett** [comment]
The definition of `\w` given by the Unicode Consortium is:

    [\p{alpha}\p{gc=Mark}\p{digit}\p{gc=Connector_Punctuation}\p{Join_Control}]

which means `\w` will match any codepoint whose General Category property is `Mark`, and there are several kinds of `Mark`.

For `"\N{VARIATION SELECTOR-16}"`, the General Category property is `Nonspacing_Mark`.

So, it's not a bug. The regex module has fuller support for Unicode that the re module.

By the way, for debugging purposes it's clearer if you use escape sequences, e.g. `"a \u2B06\uFE0F b"` or `"a \N{UPWARDS BLACK ARROW}\N{VARIATION SELECTOR-16} b"`.

**Comment by p-i-** [comment]
Thankyou for replying!
How might I extract `UP` from `'Direction: ⬆️**UP**'` using `regex`?
Currently I'm using `Direction\W*(UP|DOWN)\W*`
It seems intuitive to consider ⬆️  as a "non-word" character. It's non-spacing, but also non-word!
There may still be an issue in here...

**Comment by facelessuser** [comment]
Does any other regex engine match `fe0f` for word characters? This seems kind of wrong and unhelpful.

**Comment by facelessuser** [comment]
Hmm, it does indeed specify `mark`:
<img width="1384" alt="Screen Shot 2022-02-08 at 9 25 59 AM" src="https://user-images.githubusercontent.com/1055125/153030836-7d050f91-3514-4819-b389-915f0884fc53.png">

**Comment by facelessuser** [comment]
Seems Perl matches this, so there are others. Some engines I think simplify the `\w` definition.

**Comment by mrabarnett** [comment]
Are they simplifying or are they just less using an older definition?

As far as editors are concerned, EditPad, for example, uses `[\p{L}\p{Nl}\p{Nd}\p{Pc}]`.

**Comment by facelessuser** [comment]
You're probably right. After digging and confirming that there are others doing this and it is indeed specified in the spec, I'm satisfied. I found it surprising, but it is what it is 🙂.

**Comment by mrabarnett** [comment]
I'm just following the Unicode standard wherever possible.

If you want to include marks as non-word codepoints then try:

    Direction[\W\p{gc=mark}]*(UP|DOWN)[\W\p{gc=mark}]*

**Comment by mrabarnett** [comment]
I think it's a case of them being used in words, so they need to be treated as part of the word when you have, say, `\w+`. For example, the combining acute, grave and circumflex accents are also categorised as non-spacing marks.

**Comment by facelessuser** [comment]
Okay, that makes a bit more sense.
