### ISSUE TITLE
digit matching not working ("\d")

### ISSUE THREAD

**Issue by rimvislt** [mrabarnett/mrab-regex#455]
Why it is not matching  'b1' ?

>>> regex.match(r'\d', 'b1')
>>> regex.match(r'\d', '1b1')
<regex.Match object; span=(0, 1), match='1'>
>>> re.search(r'\d', 'b1')
<re.Match object; span=(1, 2), match='1'>

**Comment by mrabarnett** [comment]
`.match` is anchored to the start position; it doesn't search. `.search` is not anchored to the start position; it does search. There's no digit at the start of 'b1', therefore `.match` doesn't find any match.
