### ISSUE TITLE
RegexFlag exists in re, but not regex

### ISSUE THREAD

**Issue by brondsem** [mrabarnett/mrab-regex#456]
I'm trying to use `regex` as a complete replacement for `re` but I've discovered that its not fully compatible in regards to the `RegexFlag` class:

```
>>> import re, regex
>>> re.RegexFlag
<enum 'RegexFlag'>
>>> regex.RegexFlag
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'regex' has no attribute 'RegexFlag'
```

It is mentioned in the documentation at https://docs.python.org/3/library/re.html
> Changed in version 3.6: Flag constants are now instances of RegexFlag, which is a subclass of [enum.IntFlag](https://docs.python.org/3/library/enum.html#enum.IntFlag).

All the other top-level attributes `set(dir(re)) - set(dir(regex))` appear to be undocumented internals.

**Comment by mrabarnett** [comment]
Fixed in regex 2022.3.2.
