### ISSUE TITLE
Mac M1 and 2022.3.15: regex._regex_core.error: bad escape \d at position 7

### ISSUE THREAD

**Issue by tducret** [mrabarnett/mrab-regex#459]
Hi there 👋 
First, thank you very much for this great library!
I'm having the following exception while using `regex` along with the `dateparser` library:

```python
raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \d at position 7
````

**Context:**
- Mac M1
- MacOS Monterey (12.2.1)
- `regex` == 2022.3.15 _(regex-2022.3.15-cp310-cp310-macosx_11_0_arm64.whl)_
- `dateparser` == 1.1.0

**To reproduce:**
```python
import regex as re

DIGIT_GROUP_PATTERN = re.compile(r'\\d\+')
pattern = '(?P<n>\\d+) days ago|(?P<n>\\d+) day ago'
pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\d+', pattern)
```

When downgrading to version `2022.3.2`, everything works fine though.

Can you please have a look?

**Comment by mrabarnett** [comment]
Since Python 3.6, the re module has been rejecting unknown escape sequences such as `\q` in patterns and escape sequences including `\d` in replacement templates.

As the regex module no longer supports versions of Python <3.6, I've brought the regex module into line with re.

You code should now read:

    pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\\d+', pattern)

**Comment by tducret** [comment]
Thanks for the prompt answer @mrabarnett.
I'll create an issue in the `dateparser` project then (since this code is actually > https://github.com/scrapinghub/dateparser/blob/master/dateparser/languages/locale.py#L172)

**Comment by mrabarnett** [comment]
Incidentally, the code appears to be merely searching for a literal string and replacing with a literal string, so regex would be overkill anyway; using `str.replace` would be better.
