### ISSUE TITLE
Can I use this library for \K operations in Python ?

### ISSUE THREAD

**Issue by me-suzy** [mrabarnett/mrab-regex#463]
Can I use this library for \K operations in Python, such as:

```
if len(re.findall('Bebe\K.*Oana', page_text, flags=re.MULTILINE)) != 0:
    page_text =  re.sub('\1', '', page_text, flags=re.MULTILINE) 
    counter_img += 1
```

This regex will delete the word `Jumsy.` Is this possible to use `\K` for replacement?

**Comment by mrabarnett** [comment]
I don't know what you're trying to do there.

First, you're counting how many times `'Bebe\K.*Oana'` matches (I recommend using a raw string there, i.e. `r'Bebe\K.*Oana'`), but you're not interested in how many matches there are, only in whether the count is non-zero, so a search would suffice.

After that, you're replacing all occurrences of `'\1'`, which is `chr(1)` or `'\x01'`, with nothing, in the string in `page_text`, and this is unrelated to the previous search!

If you want to do a replacement, give `re.sub` the pattern and the replacement.

**Comment by me-suzy** [comment]
sorry, my mistake. Should be:

```
if len(re.findall('Bebe\K.*Oana', page_text, flags=re.MULTILINE)) != 0:
    page_text =  re.sub('Bebe\K.*Oana', '\1', page_text, flags=re.MULTILINE) 
    counter_img += 1
```

**So, the question is:** 

Is it possible to use `\K` or even `\R` with your regex library to make a FIND/REPLACE in files?

If yes, what should be the syntax for this Find and Replace with `\K`?

**Comment by mrabarnett** [comment]
`'\1'` is still `'\x01'` or `chr(1)`. What you mean is `r'\1'` or `'\\1'`, which is a reference to group 1, except that the pattern doesn't contain any groups!

Yes, you can use `\K`, but remember what it does: it changes the reported starting position of the match.

`\R` is not supported.

For example:

>>> regex.search(r'bc', 'abcd')
<regex.Match object; span=(1, 3), match='bc'>
>>> regex.search(r'b\Kc', 'abcd')
<regex.Match object; span=(2, 3), match='c'>

>>> regex.sub(r'bc', 'X', 'abcd')
'aXd'
>>> regex.sub(r'b\Kc', 'X', 'abcd')
'abXd'

**Comment by me-suzy** [comment]
I use **`\K`** and **`\G`** WORKS PERFECTLY

`<p class="mb-40px">Miracles every day <p lang="ro-RO" align="JUSTIFY">being at la home, the poet Petru Iliesu made an international appeal to condemn the killing of demonstrators, shot on the streets of town.</p>`

**And this is the regex I use in Python:**

**FIND:**

```
            if len(regex.findall('(?-i:<p class="mb-40px">|\G(?!^))(?s:(?!</p>).)*?\K(?-i:<\s*(\w+)[^/>]*>)', page_text, flags=regex.MULTILINE)) != 0:
                page_text = regex.sub(r'(?-i:<p class="mb-40px">|\G(?!^))(?s:(?!</p>).)*?\K(?-i:<\s*(\w+)[^/>]*>)', r' ', page_text, flags=regex.MULTILINE)
                counter_img += 1
```

**REPLACE BY:** `(leave empty)`

**Comment by mrabarnett** [comment]
As I said before, you're finding all of the matches, but as you're interested only in _whether_ there's a match and not in the actual number of matches, a search would suffice:

```
if regex.search(r'(?-i:<p class="mb-40px">|\G(?!^))(?s:(?!</p>).)*?\K(?-i:<\s*(\w+)[^/>]*>)', page_text, flags=regex.MULTILINE) is not None:
```

**Comment by me-suzy** [comment]
thanks
