### ISSUE TITLE
How to make Search and Replace in files ?

### ISSUE THREAD

**Issue by me-suzy** [mrabarnett/mrab-regex#465]
good day. I want to make a Search and Replace in files. I usually use this method:

```
for p in re.findall(r'^(?!<p class="mb-40px">)(.+?)(</p>)', paragraphs[i], flags=re.MULTILINE):
      p = re.sub(r'^(?!<p class="mb-40px">)(.+?)(</p>)', r'<p class="mb-40px">\1\2', p, flags=re.MULTILINE)
```

but I can't make it work with this extension. Maybe I'm doing something wrong, please see. I use: for testing **regex.match** for find and  **regex.sub** for replace.

```
for p in regex.search(r'^(?!<p class="mb-40px">)(.+?)(</p>)', paragraphs[i], flags=re.MULTILINE):
      p = regex.sub(r'^(?!<p class="mb-40px">)(.+?)(</p>)', r'<p class="mb-40px">\1\2', p, flags=re.MULTILINE)
```

This is the error:

```
Traceback (most recent call last):
  File "E:\Carte\BB\aprilie.py", line 250, in <module>
    if len(regex.search(paragraph_pattern, paragraphs[i])) != 0 or len(regex.search(r'^(?!<p class="mb-40px">)(.+?)(</p>)', paragraphs[i], flags=re.MULTILINE)) != 0:
  File "C:\Users\Castel\AppData\Roaming\Python\Python310\site-packages\regex\regex.py", line 267, in search
    pat = _compile(pattern, flags, ignore_unused, kwargs, True)
  File "C:\Users\Castel\AppData\Roaming\Python\Python310\site-packages\regex\regex.py", line 509, in _compile
    raise TypeError("first argument must be a string or compiled pattern")
TypeError: first argument must be a string or compiled pattern
```

**Comment by mrabarnett** [comment]
In the second example, you wrote `regex.search` instead of `regex.findall`. That's why it's complaining.

Another point: in the second example, you're passing flags defined in the re module (`re.MULTILINE`, etc.), to functions defined in the regex module. Don't do that. Use re flags with the re module and regex flags with the regex module.

**Comment by me-suzy** [comment]
thanks for answer. Ok, just one thing. I don't understand how to use re flags with the re module and regex flags with the regex module. ?!

can you please modify my second example and put the right answer, to make sure I understood everything perfectly ?

**Comment by mrabarnett** [comment]
You're already using re flags in the first example when you wrote `re.MULTILINE`.

To use the regex module instead of the re module, just replace `import re` with `import regex` and write `regex` where you would have written `re` previously.

Do that to the first example and you get this:

```
for p in regex.findall(r'^(?!<p class="mb-40px">)(.+?)(</p>)', paragraphs[i], flags=regex.MULTILINE):
      p = regex.sub(r'^(?!<p class="mb-40px">)(.+?)(</p>)', r'<p class="mb-40px">\1\2', p, flags=regex.MULTILINE)

```

**Comment by me-suzy** [comment]
so, I cannot use both `import re` and `import regex ` in the same time ?

**Comment by mrabarnett** [comment]
You _can_ import them both. What you shouldn't do is assume that flags defined by one will be understood by the other.

**Comment by me-suzy** [comment]
thank you very much. So, not to forget to import this:

```
import regex

```

**Comment by mrabarnett** [comment]
Why do you want to import `_regex`? That's an internal details of the `regex` module.
And the `collections` module is unrelated to the `regex` module, so I don't know why you're mentioning it!

**Comment by me-suzy** [comment]
sorry, I delete the collection module. So, that wasn't necessary.
