### ISSUE TITLE
Tie breaker for BESTMATCH during fuzzy match?

### ISSUE THREAD

**Issue by yjqiu** [mrabarnett/mrab-regex#466]
The fuzzy search with custom cost is an excellent feature. But I wonder how the program breaks tie when two matches are equal in cost.

For example, if I have `{s<=2, i<=1, s+2i<=3}` as the criteria for fuzzy search. A match with 2 substitutions will have same cost as one insertion, and either of them will satisfy the criteria. In that case, which one will be reported as match?

**Comment by mrabarnett** [comment]
It tries to minimise the total number of errors while remaining within any specified limits, i.e. minimise `s+i+d`, where `s<=2`, `i<=1`, and `s+2i<=3`.

**Comment by yjqiu** [comment]
@mrabarnett Thanks for the quick reply! Any rules to place the substitutions or gaps when the number of errors are the same? See both matches have 2 substitutions but at different places. Which one will it pick?

**Comment by mrabarnett** [comment]
Can you give me an example?

**Comment by yjqiu** [comment]
For example, AC can match to AAT at either AA or AT and both matches have one substitution.

**Comment by mrabarnett** [comment]
It would return the first match, as is usual for regexes.

**Comment by yjqiu** [comment]
@mrabarnett Thanks for the detailed explanation and quick response!
