### ISSUE TITLE
Positive lookahead and non greedy quantifier issue

### ISSUE THREAD

**Issue by andiandi13** [mrabarnett/mrab-regex#468]
I'm using this code :

```
import regex

PATTERN = regex.compile(r"(?<=\\fn).*?(?=\\)")

print(PATTERN.findall("\\fn\\b1\\"))
```

To match the empty string between \fn and \b1

`\\fn\\b1`

But it returns :

`['', '\\b1']`

What I would like is rather :

`['']`

I can't understand what the issue might be.

________________

_Note that if I add a whitespace between \\fn and \\b1:_

`print(PATTERN.findall("\\fn \\b1\\"))`

_It returns :_

`[' ']`

**Comment by mrabarnett** [comment]
It's an odd edge case.

Basically, `.findall` (and `.finditer`) can return contiguous matches:

```
>>> regex.findall(r".", "abc")
['a', 'b', 'c']
```

but, after a zero-width match, it's not allowed to return another contiguous zero-width match, so this is OK:

```
>>> regex.findall(r".*", "abc")
['abc', '']
```

However, it means that this is also OK, although surprising:

```
>>> regex.findall(r".*?", "abc")
['', 'a', '', 'b', '', 'c', '']
```

The re module does the same:

```
>>> re.findall(r".", "abc")
['a', 'b', 'c']
>>> re.findall(r".*", "abc")
['abc', '']
>>> re.findall(r".*?", "abc")
['', 'a', '', 'b', '', 'c', '']
```

**Comment by moi15moi** [comment]
That's not my issues, but I find this pretty strange.

If I try to use his regex in C# with regex101, it does what @andiandi13 want.

![image](https://user-images.githubusercontent.com/80980684/165407562-cc457056-cca1-41f7-8729-427c0d11088e.png)

I don't see why it would be **normal** that it match with the \\b1.

Same for your example with abc. I understand that re module works like that, but, to me, it is still strange that it work like that.

**Comment by mrabarnett** [comment]
Well, Perl 5.20 finds 2 matches.

That's the problem with regex: there's no commonly-agreed standard, just a number of implementations with differing features and sometimes subtly different behaviours.

The regex module was, after all, written to be compatible with Python's re module.

**Comment by moi15moi** [comment]
Ok, so this is litteraly impossible to do what andiandi want even with another regex?

**Comment by mrabarnett** [comment]
Instead of using a lazy repeat to match up to a terminator, use a greedy repeat to match what's not a terminator and capture it in a group.

As the terminator is a single character, a negated character set would do:

```
>>> regex.findall(r"(?<=\\fn)([^\\]*)", "\\fn\\b1\\")
['']
```

If the terminator is longer than one character, then 'consume' characters while you haven't arrived at the terminator:

```
>>> regex.findall(r"(?<=\\fn)((?:(?!end).)*)", "\\fnend")
['']
```
