### ISSUE TITLE
Python 3.11 is not supported

### ISSUE THREAD

**Issue by KhDenys** [mrabarnett/mrab-regex#476]
If there are some plans to bring support of python 3.11?

**Comment by mrabarnett** [comment]
I will add wheels for Python 3.11 when the final release of Python 3.11 arrives. Until then, this package can be installed from the source distribution if your system is set up for that.

**Comment by C-Ezra-M** [comment]
It does work properly in 3.11.

```pycon
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import regex as re
>>> re.search(r"\p{Lu}", "małĄ")
<regex.Match object; span=(3, 4), match='Ą'>
>>> re.search(r"\pL", "małĄ")
<regex.Match object; span=(0, 1), match='m'>
>>>
```

Possessive quantifiers (`*+`, `++`, `?+`, `{m,n}+`) and atomic groups (`(?>...)`) can be ignored when executing the module in 3.11, since the core `re` module added support for them. However, I don't know if it's possible if this package is mostly based on a C extension. Probably there is a low-level equivalent to `sys.versioninfo`...?

**Comment by makyen** [comment]
@Keyacom Why would Possessive quantifiers and atomic groups be ignored in this module, ever?

From the fact that you've said that they should be ignored, I'd assume that you haven't understood that this is a *complete, separate* implementation of a regular expression engine. It does try to maintain API compatibility and `re`->`regex` regular expression syntax compatibility with the `re` module, but it doesn't *use* the `re` module.

**Comment by C-Ezra-M** [comment]
> [...] I'd assume that you haven't understood that this is a _complete, separate_ implementation of a regular expression engine. [...]

I haven't even realized that.

**Comment by KhDenys** [comment]
@mrabarnett 

> I will add wheels for Python 3.11 when the final release of Python 3.11 arrives. Until then, this package can be installed from the source distribution if your system is set up for that.

Do you have any update?

**Comment by mrabarnett** [comment]
The wheels are already there, I just haven't updated the main page yet. It used to be possible to update just the main page, but now it requires a full release, which can take a while.

**Comment by mrabarnett** [comment]
regex 2022.10.31 is now on the way. It's just updated text. It already supports Unicode 15.0.0 and Python 3.11.
