### ISSUE TITLE
Grapheme segmentation

### ISSUE THREAD

**Issue by djstrong** [mrabarnett/mrab-regex#481]
Why emojis with multiple skin tones (e.g. 🧑🏼🏼🏼) are treated as one grapheme? IMO additional skin tones should be separate graphemes.

Also, I don't like some Hangul sequences treated as one graphemes, e.g. ᄅᄅᄅ.

**Comment by mrabarnett** [comment]
As far as I can tell, I'm following the Unicode specification at https://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries.
