### ISSUE TITLE
Regex constrain fuzzy search

### ISSUE THREAD

**Issue by ayaanhossain** [mrabarnett/mrab-regex#484]
Thanks for this great library! I'm considering using this for one of my projects, but was stuck on a seemingly trivial fuzzy matching case.

If I have a pattern that I want to match in a larger text, I know how to specify the total number of ins/sub/del operations, and threshold the total cost. But is there any way to specify not to do certain operations on certain parts of the pattern, or force certain operations within certain regions to while maintaining the total cost?

For example, if I want to match a pattern while preventing insertion or deletion on the first and last characters of the pattern (subs are fine) but allowing it elsewhere, while keeping the total overall cost within some threshold? Or force specific operations on specific parts, say insertion and deletion operations only on the last five characters while capping the total cost within some bounds?

Any pointers would be helpful.

**Comment by mrabarnett** [comment]
I suppose you could try putting additional constraints on those portions, i.e. a fuzzy match within a fuzzy match, but the outer fuzzy match might will still allow the unwanted operations just next to the inner fuzzy match. Alternatively, you could try using fuzzy matches within lookahead and lookbehind to impose further limits on the ends. I don't know how well that would work either, however.
