### ISSUE TITLE
negative lookbehind/-ahead returned as None in .groups()

### ISSUE THREAD

**Issue by yan-hic** [mrabarnett/mrab-regex#485]
if not matched negative lookbehind or -ahead groups are None but why would they be returned by search.groups() ?

Is there anyway to get only the capturing groups ?

I guess I could filter all `None` groups but wonder why they were included in the first place.

**Comment by mrabarnett** [comment]
What if the negative lookahead contained a capture group and a backreference to that group? There must be a way to refer to that group. Plus, that's what the `re` module does.

**Comment by yan-hic** [comment]
Makes sense. Thanks @mrabarnett
