### ISSUE TITLE
Will it be better if partial match returns the match part rather None?

### ISSUE THREAD

**Issue by y9c** [mrabarnett/mrab-regex#489]
Take this snippet as an example

```
m = regex.rearch("(aa)(\d+)(bb)", "aa123b", partial=True)
print(m.groups())
```

The return would be `('aa', '123', None)`. 

Will it be more reasonable if the return includes the partial matched one, which would become `('aa', '123', 'b')`?

**Comment by mrabarnett** [comment]
It captures only when it reaches the end of the group, which it wasn't able to do. It's been like that since partial matching was introduced.
