### ISSUE TITLE
Feature Request: Namespaced Named Match Groups

### ISSUE THREAD

**Issue by SysAdminNoir** [mrabarnett/mrab-regex#492]
I am working on a custom log analysis tool for work, and I have a lot of matching to go through over a lot of separate logs (GBs of client supplied logs). I need to match some values from logs against others and hold these matches in a class/dictionary/whatever while I go through them.

Usually when performing this task, I use regex, a TON of regex. I know it pretty well. I prefer to use named match groups vs. indexed, as I really don't like to go back and forth to try to remember what the index is to what I matched. This is really, really tiresome when you have more than a handful to deal with.

Since I use multiple regex strings, it's far easier to join them in a "super-regex" using OR/disjunction syntax then to perform a match using each one separately (so long as those "sub-regex" don't have a disjunction in them themselves, usually never occurs). The code is shorter, and in my limiting testing seems to be more performant to have all the heavy lifting done in the regex engine (empirical evidence, and more opinion than fact).

Basically, I'm trying to reduce the number of match/if statements and instead just dump the values into a dict/object, etc. 

What I would like to do is get some easy method to "namespace" my matchgroups.

For example (not the actual regexes, can't really show the actual log values):
```    
import re
    
regex_example_simple = r'CUSTOMERDB.*?Name:(?P<name>\w+)'
regex_example_complex = r'CLIENTDB.*?DB Index:(?P<DBIndex>\d+);.*?Name:(?P<name>);.*?City:(?P<city>[\w]+).*?Value:(?P<Value>\d+)'

REGEX_ALL = re.compile('|'.join('({0})'.format(x) for x in (regex_example_simple, regex_example_complex)))
```

Here we can see a collision, and Python will helpfully throw a `re.error: redefinition of group name` error due to "name" being, well, named the same group name. 

I understand this library supports multiple match groups named the same, and overwrites to the last occurrence, but this is not the functionality I am looking for. A bit opposite actually, I want some method of preserving the named match groups, but namedspaced so they can be filtered.

So maybe we could have a `NAMESPACED` flag that indicates that the dot character can be used within group names to specify a namespace postfix: `(?P<IDENTIFIER.NAMESPACE>)`

Then when matching we simply return the full group namespaced group name under a new method called `capturesnamedspacedict()` or something like that.

For example:
```
import regex

simple = 'CUSTOMERDB.*?Name:(?P<name.simple>\w+);') 
complex = 'CLIENTDB.*?DBIndex:(?P<DBIndex.complex>\d+);.*?Name:(?P<name.complex>\w+);.*?City:(?P<city.complex>[\w]+);.*?Value:(?P<Value.complex>\d+)')

REGEX_ALL = re.compile('|'.join('({0})'.format(x) for x in (simple, complex)))

Line1 = "CUSTOMERDB:12345;Name:Jason;\n"
Line2 = "CLIENTDB:6789;DBIndex:00001;Something else here;Name:Newt;Something else here;City:London;Something;Value:1000000;"

m1 = regex.match(REGEX_ALL, Line1, flags=regex.NAMESPACED)
capture1 = m1.capturesnamedspacedict()

# capture1 = {'name.simple': 'Jason'}

m2 = regex.match(REGEX_ALL, Line2, flags=regex.NAMESPACED)
capture2 = m2.capturesnamedspacedict()

# capture2 =  {'name.complex' : 'Newt', 'DBIndex.complex' : '00001', 'City.complex' : 'London', etc etc}
```

Maybe this is a completely stupid idea limited to just my very specific use case, but I'm surprised this has never been brought up before. It would seem to me to be very useful.

**Comment by SysAdminNoir** [comment]
Now that I think about it, an inline flag could be used to obviate the need to add a namespace postfix to the group name. Maybe something like this:

`(?NAMESPACE:complex)`

Then the return of `capturesnamedspacedict()` could be automatic and avoid having to add the namespace to each group name.

**Comment by mrabarnett** [comment]
Group names must be a valid identifier, but that still gives you a lot of characters to play with. It's valid as long as `str.identifier()` returns True.

For example, `'foo_bar'.isidentifier() == True` and `'foo\xB7bar'.isidentifier() == True`: `'foo\xB7bar'` looks like `foo·bar` (U+00B7 is `'\N{MIDDLE DOT}'`).

**Comment by SysAdminNoir** [comment]
Thank you, this is very helpful. I may have to make my own class that can use this "behind the scenes".

But a question: it appears that your implementation goes beyond standard Python syntax, and you have added some additional features. Would you consider this possibly in the future? Even distant?

**Comment by mrabarnett** [comment]
I'm not planning on adding any more features as it has a lot of them already.
