### ISSUE TITLE
Non deterministic finditer matching

### ISSUE THREAD

**Issue by creat89** [mrabarnett/mrab-regex#493]
Hello,

I'm having issues with a regular expression that is behaving non deterministically. Sometimes it finds the pattern correctly, but most of the time it doesn't. This is the pattern `(?<=\b|\s|^)§\s*\d+(?=\b|\s|$)`, which is compiled once. And here is the text as input: `articles 9§4 and 8§2 of the Agreement`. I would expect as matches `§4` and `§2`. In most of the cases it only find the second match but not the first when using `finditer`.

Here is a snippet of how everything is running:
```
...
pattern = regex.compile(rf"(?<=\b|\s|^){line}\s*\d+(?=\b|\s|$)")
...
for match in regex.finditer(pattern, text):
...
```

I'm using regex==2022.10.31

I have tested V0 and V1 without success.

**Comment by mrabarnett** [comment]
I cannot reproduce the issue.

I notice that you wrote:

`pattern = regex.compile(rf"(?<=\b|\s|^){line}\s*\d+(?=\b|\s|$)")`

Are you sure that `line` is what you think it is?

**Comment by creat89** [comment]
Ok, the issue doesn't come from the regex library. It comes from creating a set from the matches found, which doesn't keep the order always. That is why my test was was failing.
Sorry.
BTW, amazing library.
