### ISSUE TITLE
Support `pyproject.toml` build mechanism (PEP-517)

### ISSUE THREAD

**Issue by ghost** [mrabarnett/mrab-regex#496]
`pip` 23.1+ (2023-04-15) use `pyproject.toml` build, `setup.py` build is on the deprecated way.
https://github.com/pypa/pip/blob/main/NEWS.rst#231-2023-04-15

Just three steps to support `pyproject.toml` build, then [this failing CI](https://github.com/mrabarnett/mrab-regex/actions/runs/4503579068/jobs/7926946983) can be fixed.

1, add a `pyproject.toml` file at the root folder that has `setup.py`, the content only has 3 lines:
```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

2, add `pyproject.toml` to `MANIFEST.in`.

3, modify `.github/workflows/main.yml`, to use the new build way:
```diff
@@ -30,7 +30,7 @@ jobs:
 
       - name: Run test
         run: |
-          python setup.py install
+          python -m pip install -vv .
           python -m unittest -v regex.test_regex
 
   # Build Linux/macOS/Windows wheels.
```

BTW, `.hgeol` can be removed, it was for Mercurial.

**Comment by mrabarnett** [comment]
Thanks for you contribution. Done in regex 2023.5.2.

**Comment by ghost** [comment]
The commit 16bcce0 CI fails because Python 3.6 (docker?) image doesn't have recent versions of setuptools module. Remove this `>=61.0` should fix.

**Comment by ghost** [comment]
pyproject.toml can only has 3 lines, or some information are duplicated in setup.py and pyproject.toml.

**Comment by ghost** [comment]
In the two files, `requires-python = ">=3.x"` are not consistent, one it's 3.6, the other it's 3.8.

**Comment by mrabarnett** [comment]
Sorry about that! Fixed in regex 2023.5.4.

**Comment by ghost** [comment]
GCC has some compile warnings:
https://github.com/mrabarnett/mrab-regex/actions/runs/4863656058/jobs/8671648027#step:4:104

**Comment by mrabarnett** [comment]
Thanks for that. It's annoying that Visual Studio didn't warn me. Fixed in regex 2023.5.5.

**Comment by ghost** [comment]
Only one warning was fixed, the others still exist.
You can install a WSL Linux, and build in it.

**Comment by mrabarnett** [comment]
Only the one I fixed was an actual bug.
