### ISSUE TITLE
Confusion with characters before/after fuzzy substring match

### ISSUE THREAD

**Issue by schance995** [mrabarnett/mrab-regex#497]
I want to match a pattern starting and ending with A, which has 6 A's in the middle and at most 2 substitutions.

Why does this regex not print the sequences of A's after the G's? Is this a bug or is something wrong here?
```
>>> regex.match(r"A(A{6,}){s<=2}A", "AAAAGGGAAAAAAAAAAAAAAAAA")
>>> 
>>> regex.match(r"A((A{6,}){s<=2})A", "AAAAGGGAAAAAAAAAAAAAAAAA")
>>> 
>>> regex.match(r"A(AAAAAA){s<=2})A", "AAAAGGGAAAAAAAAAAAAAAAAA")
>>> 
```

**Comment by mrabarnett** [comment]
Match A:

    AAAAGGGAAAAAAAAAAAAAAAAA
    ^

Then try to match 6 of A:

    AAAAGGGAAAAAAAAAAAAAAAAA
     ^----^

That doesn't match because it would require 3 substitutions.

You're using `regex.match`, which is anchored at the start of the string, so no match is possible.

If you used `regex.search` instead, then it would be able to match.
