### ISSUE TITLE
Strings containing other scripts are not properly matched

### ISSUE THREAD

**Issue by damiaanr** [mrabarnett/mrab-regex#502]
The following string:

`s = r'ሕዚ እውን ሸለልትነት ኣወጊድና ኩሎም ዝተነፀሩ መከላኸሊ ሜላታት ብምትግባር ቫይረስ ኮሮና ክንከላኸል ይግባእ - ዶ/ር ደብረፅዮን ገ/ሚካኤል - Welcome to Fana Broadcasting Corporate S.C'`

With the following simple RegEx pattern:

`r = r'[A-Za-z]'`

Does not return a match upon regex.match (of course after compiling regex.compile). Other strings, such as 'hello', do return matches.

I observe the same behaviour for strings containing other scripts (such as Han-script, etc.)

Am I doing something wrong here, or is this a bug of some sorts? Python version is 3.9.13.

(The real pattern that I am using is much more complicated, combining several \p{}-symbols with others, like A-Za-z, etc.)

**Comment by 5j9** [comment]
Try `regex.search` instead of `regex.match`. [Match only matches at the beginning of the string](https://docs.python.org/3/library/re.html#re.Pattern.search).

**Comment by damiaanr** [comment]
Thank you. All I can say is: excuse me for littering here with such a stupid question.

**Comment by mrabarnett** [comment]
Don't worry about it! Occasionally someone makes the same mistake with `re`, too.
