### ISSUE TITLE
Capturing repeated groups

### ISSUE THREAD

**Issue by Mark531** [mrabarnett/mrab-regex#504]
I want to match a regexp and then retrieve all the captured groups.
This regexp fails, only the last group is stored:
```
m = regex.match("^([^\t]+)(?:\t([^\t]+))*$", "this\tis\ta\ttest")
m.groups()
```

> ('this', 'test')

It's a known limitation of the _re_ package, but I thought it was solved by _regex_. Isn't it the case?

**Comment by mrabarnett** [comment]
That pattern has 2 groups, therefore `.groups()` returns a 2-tuple.  That behaviour is common to all regex implementations.

If you want all of the strings that were captured by a group, use the `.captures(...)` method:

```
>>> import regex
>>> m = regex.match("^([^\t]+)(?:\t([^\t]+))*$", "this\tis\ta\ttest")
>>> m.groups()
('this', 'test')
>>> m.captures(1)
['this']
>>> m.captures(2)
['is', 'a', 'test']
```

The parameters of `.captures(...)` are the same as those of `.group(...)`.
