### ISSUE TITLE
How to “verbose” my regex pattern?

### ISSUE THREAD

**Issue by Listine** [mrabarnett/mrab-regex#507]
Hello,
I tried to compile the regex pattern in the same way I would do with the Python regex to “verbose” it:
my_pattern = regex.compile("""pattern line 1
                                               pattern line 2
                                               pattern line 3""", regex.VERBOSE)

It doesn’t seem to work… An idea? Please? Thanks.

**Comment by 5j9** [comment]
What do you mean by "It doesn’t seem to work"? Does it raise an error? Does it not match? If it does not match, what is the string that you're trying to match against? Seems to be working for me:
```python
import regex
string = """pattern line 1
pattern line 2
pattern line 3"""

my_pattern = regex.compile(string, regex.VERBOSE)

print(my_pattern.match(string.replace('\n', '').replace(' ', '')))
# prints: <re.Match object; span=(0, 36), match='patternline1patternline2patternline3'>
```

**Comment by mrabarnett** [comment]
It's also working for me as expected.

**Comment by Listine** [comment]
I’m sorry I have been so vague. Actually, it doesn’t work in a special case: with the \K thing.
```
import regex as reg
motif_objet2= reg.compile("""ACHAT CB \KSNCF|ACHAT|retrait|
                            sfr\sfixe|mobile|frais\sde\stenue|eau|LBP\sIARD|engie""", reg.VERBOSE|reg.IGNORECASE)

def reg_objet_2(x):
    result = motif_objet2.search(x)
    if result != None:
        return result.group()
    else:
        return x

df = pd.Series(['ACHAT CB AUX 4 SAISONS 12.07.23 CARTE NUMERO 054',
               'CARTE X332 19/05/23 A 9H00 RETRAIT DAB LA BANQUE POSTALE',
               'ACHAT CB SNCF 22.06.23 CARTE NUMERO 017',
               'PRELEVEMENT DE LBP IARD REF : 658213389  NP221345324 IDENT : GO43241217'])
df.apply(lambda x : reg_objet_2(x))
```
With VERBOSE, I don’t get SNCF for the third line, but I get it with the MULTILINE flag.

**Comment by facelessuser** [comment]
Are you sure you didn't forget to use a raw string `r"""`? I haven't verified your code, but it appears you need to use a raw string.

**Comment by Listine** [comment]
I added the little r before the string of the pattern… no difference.

**Comment by mrabarnett** [comment]
In order to match `'SNCF'`, it must first match `'ACHAT CB '`, which contains spaces, but the `VERBOSE` flag tells it to ignore whitespace in the pattern except in character sets, so `'ACHAT CB \KSNCF'` with the verbose flags is equivalent to `'ACHATCB\KSNCF'`.

You need to escape any whitespace in the pattern that needs to be kept, so `'ACHAT CB \KSNCF'` should be `'ACHAT\ CB\ \KSNCF'`.

Writing the pattern as a raw string is good idea:

```
motif_objet2= reg.compile(r"""ACHAT\ CB\ \KSNCF|ACHAT|retrait|
                            sfr\sfixe|mobile|frais\sde\stenue|eau|LBP\sIARD|engie""", reg.VERBOSE|reg.IGNORECASE)
```

**Comment by Listine** [comment]
Thank you, Mr Barnett (and the other contributors too). Mystery solved.
(I used \s instead of \ ).
