### ISSUE TITLE
universal2 wheel not currently available

### ISSUE THREAD

**Issue by fluffy-critter** [mrabarnett/mrab-regex#511]
I see from issue #399 that there should now be a universal2 bdist for this package. However, as of version 2023.10.3, I'm only seeing separate arm64 and x64 bdists, which means extra steps to build a package for binary distribution via pyInstaller or the like.

Was support for universal2 disabled on purpose, or is this a regression in the build setup?

As a workaround I can build my own universal2 build and upload it to a devpi instance (as I have to do for a couple other dependencies anyway) but I'd definitely prefer to not have to do this every time regex updates.

Thanks!

**Comment by mrabarnett** [comment]
As you can see from that issue, I switched to GitHub 2 years ago, so now wheels are built with GitHub Actions, and this is the time someone has asked about universal2 wheels!

Do you know how to build them with GitHub Actions? What changes would I have to do in [main.yml](https://github.com/mrabarnett/mrab-regex/blob/hg/.github/workflows/main.yml)?

**Comment by fluffy-critter** [comment]
I have no idea. I’m pretty new to this issue myself; the need for a universal2 bdist is pretty rare these days (you basically only need it when making a standalone installable application on macOS) so it isn’t too surprising this hasn’t come up very often.

**Comment by fluffy-critter** [comment]
It looks like all you have to do is add `universal2` to `CIBW_ARCHS_MACOS`.

**Comment by mrabarnett** [comment]
Thanks for that. I've updated my local copy of `main.yaml` so it should be in the next release. I don't think it's worth making a complete new release now for this.

**Comment by fluffy-critter** [comment]
Yeah, totally understandable. I already have a workaround in my own project, anyway, and this will just be helpful for others in the future. Thanks!
