### ISSUE TITLE
Repeated patterns does not work with findall

### ISSUE THREAD

**Issue by TristanM42** [mrabarnett/mrab-regex#512]
I tried the documentation example of repeated pattern with regex.findall but it's not working, only regex.match is correct.
My version of regex is 2022.9.13.

>>> import regex
>>> regex.match(r"(Tarzan|Jane) loves (?1)", "Tarzan loves Jane")
<regex.Match object; span=(0, 17), match='Tarzan loves Jane'>
>>> regex.match(r"(Tarzan|Jane) loves (?1)", "Tarzan loves Jane").groups()
('Tarzan',)
>>> regexx = regex.compile('('+r"(Tarzan|Jane) loves (?1)"+')')
>>> m = regexx.findall("Tarzan loves Jane")
>>> m
[]
>>> regexx
regex.Regex('((Tarzan|Jane) loves (?1))', flags=regex.V0)

**Comment by mrabarnett** [comment]
Look more closely at the pattern `((Tarzan|Jane) loves (?1))`.

There are 2 groups, and `(?1)` is calling the first (outer) group, but it's doing so from *inside* that group.

You're telling to match the pattern `(Tarzan|Jane) loves ` followed by the pattern in group 1, which is `(Tarzan|Jane) loves ` followed by the pattern in group 1, which is `(Tarzan|Jane) loves ` followed by the pattern in group 1, which is ...

**Comment by TristanM42** [comment]
oh right ... i dont know why i decided to add extra parenthesis in the first place... sorry for the issue, i tested it and it works as expected 👍

EDIT : _i dont know why i decided to add extra parenthesis in the first place._ --> when using group(s) in a pattern, the group 0 (whole match) is not given in the result of findall. Only in the case where there is no group in the pattern, then findall return the whole match (since there is nothing else to return).

So that's why i added parenthesis, to make the function more consistent, with first result of each tuple being the whole match. But i guess that's a personal preference.
