### ISSUE TITLE
Wrong partial match result when using lookahead with .* wildcard

### ISSUE THREAD

**Issue by CompilerCrash** [mrabarnett/mrab-regex#514]
Hi, please take a look at this code: 
```python
import regex as re

pattern = r"hello(?=.*world)( mom| dad| world)+"
string = "hello moon"
match = re.fullmatch(pattern, string, partial=True)
print(match)
```
Intuitively, `pattern` describes a string that starts with "hello", followed by the words "mom", "dad", and "world" in any order and number, but "world" must appear at least once.

This works fine when using full matches (`partial=False`). But when I change to partial matches, as shown in the example above, I get unexpected results. As "moon" is not among the allowed words, there is no way how "hello moon" can be/become a match. Yet I get `<regex.Match object; span=(0, 10), match='hello moon', partial=True>`.

I'm using regex v2023.10.3

**Comment by mrabarnett** [comment]
I think the problem is that it's finding a partial match when it does the lookahead and it's not looking any further, so it's doesn't see that what follows the lookahead will never match anyway, not even partially.

**Comment by CompilerCrash** [comment]
That sounds plausible. It would be great if you could fix it.

**Comment by mrabarnett** [comment]
I've decided to leave it as it is. The current behaviour is at least predictable - it says it's partial as soon as it hits the end of the string. Changing the behaviour just leads to a whole load of cases where it's not clear what the result should be or how it could be implemented.

**Comment by CompilerCrash** [comment]
Yes, the lookahead hits the end of the string, but (since the lookahead doesn't consume any characters) the actual parsing does not – yet it's terminated prematurely.

The current behavior boils down to "if there is a `.*` in the lookahead, you will always get a (partial) match", which is not very useful IMHO.

From my understanding, the parsing should simply continue after the lookahead is finished, taking the lookahead result into account as follows:
```
T = full match
P = partial match
F = no match

           Lookahead
           T P F
Rest    T  T P F
of the  P  P P F
string  F  F F F
```

That said, you know the implementation and can judge better than me, how intricate it would be to change the current behavior. Also, maybe I'm missing something and there are cases where it's less clear what the correct result should be.

Fortunately, I think I found a workaround for my specific use case.

**Comment by mrabarnett** [comment]
Here's an example using `(?=.(.))\1`.

Current behaviour:
```
>>> print(regex.match(r'(?=.(.))\1', 'a', partial=True))
<regex.Match object; span=(0, 1), match='a', partial=True>
>>> print(regex.match(r'(?=.(.))\1', 'aa', partial=True))
<regex.Match object; span=(0, 1), match='a'>
```

Your suggested behaviour:
```
>>> print(regex.match(r'(?=.(.))\1', 'a', partial=True))
None
>>> print(regex.match(r'(?=.(.))\1', 'aa', partial=True))
<regex.Match object; span=(0, 1), match='a'>
```

With your suggested behaviour, matching against `'a'` will fail because the group didn't capture (it has already reached the end of the string), but matching against `'aa'` will succeed.

**Comment by CompilerCrash** [comment]
Ah, I see. That's certainly not a desirable behavior, either. I get the feeling that partial matches and lookaheads generally don't go well together, and it might be better to avoid using them in the first place. Anyway, thanks for considering my request and for pointing out the issues with it.
