### ISSUE TITLE
Why does this regex formula doesn't work in Python for Find and Replace?

### ISSUE THREAD

**Issue by me-suzy** [mrabarnett/mrab-regex#516]
I need to delete all `"` from the html tag: `<meta name="description" content=".*?">`

`<meta name="description" content="La Spitalul " Primului Popor din provincia Yunnan, un tânăr pacient a bănuit că are o tumoare și a venit la examinare. Song Zhengji, directorul Departamentului de Gastroenterologie de la Spitalul Primului Popor din provincia Yunnan, a declarat că spitalul a tratat recent mulți pacienți care au fost bolnavi după ce au mâncat Tu Panax. Song Zhengji a spus că toxicitatea rizomilor "Tu Panax notoginseng" este și mai mare atunci când sunt înmuiate în alcool. Alcoolul va extrage toxinele, va deteriora vasele de sânge, va provoca blocaj hepatic, va cauza leziuni hepatice, ascită și chiar insuficiență hepatică. ">`

**Why doesn't work this regex, while in notepad++ works good:**   `(?-s)(?-i:<meta name="description" content="|(?!\A)\G).*?\K(?-si:")(?=(?s-i:.*?">))`

```
        def remove_double_quotes(html_content):
            regex = re.compile(r'(?-s)(?-i:<meta name="description" content="|(?!\A)\G).*?\K(?-si:")(?=(?s-i:.*?">))')
            return regex.sub('', html_content)
```

**Or another version, that also doesn't work:**  `(?-s)(?-i:<meta name="description" content="|(?!\A)\G).*?\K"(?!">)`

```
        def remove_double_quotes(html_content):
            pattern = regex.compile(r'(?-s)(?-i:<meta name="description" content="|(?!\A)\G).*?\K"(?!">)')
            return pattern.sub('', html_content)
```
**The entire code here: Don't have error. Except, doesn't replace on text files**

```
import regex

def remove_double_quotes(html_content):
    # Folosind regex.compile pentru a compila expresia regex
    pattern = regex.compile(r'(?s:<meta name="description" content="|(?!\A)\G).*?\K"(?!">)')
    return pattern.sub('', html_content)

html_content = """
<meta name="description" content="La Spitalul 'Primului Popor' din provincia Yunnan, un tânăr pacient a bănuit că are o tumoare și a venit la examinare. Song Zhengji, directorul Departamentului de Gastroenterologie de la Spitalul Primului Popor din provincia Yunnan, a declarat că spitalul a tratat recent mulți pacienți care au fost bolnavi după ce au mâncat Tu Panax. Song Zhengji a spus că toxicitatea rizomilor 'Tu Panax notoginseng' este și mai mare atunci când sunt înmuiate în alcool. Alcoolul va extrage toxinele, va deteriora vasele de sânge, va provoca blocaj hepatic, va cauza leziuni hepatice, ascită și chiar insuficiență hepatică.">
"""

new_html_content = remove_double_quotes(html_content)

print(new_html_content)

```

**Comment by mrabarnett** [comment]
You didn't say in what way it "doesn't work", so I'm guessing that you're talking about the exception `bad inline flags: cannot turn flags off at position 5`.

The `regex` module is intended to be compatible with the `re` module, and that module (currently Python 3.12) also raises an exception.

Historically, in the `re` module, inline flags auch as `(?s)` applied to the entire pattern, no matter where they appeared, whereas in other implementations they applied only to what followed, assuming that they were supported at all.

Recent versions of the `re` module have shown a warning (Python 3.10) or raised an exception (Python 3.11-3.12) if the inline flag isn't at the start because the intention is to have the other behaviour, and it's raising an exception so that users are first moved away from the old behaviour.

The behaviour of `regex` will change too, when that of `re` changes.

In the meantime, try this pattern: `(?-si:<meta name="description" content="|(?!\A)\G)(?-s:.*?)\K(?-si:")(?=(?s-i:.*?">))`

**Comment by me-suzy** [comment]
Your pattern doesn't work.

**But I find another good solution:**

```
import os
import regex

def remove_double_quotes_from_meta(html_content):
    # Regex pentru a identifica tagurile meta și pentru a înlocui ghilimelele din atributul content
    pattern = regex.compile(r'(<meta name="description" content=")(.*?)(">)', regex.DOTALL)

    def replace_quotes(match):
        # Eliminarea ghilimelelor din conținutul atributului content
        content_without_quotes = match.group(2).replace('"', '')
        return match.group(1) + content_without_quotes + match.group(3)

    # Înlocuirea ghilimelelor în toate tagurile meta potrivite
    return pattern.sub(replace_quotes, html_content)

def process_html_files(folder_path):
    for filename in os.listdir(folder_path):
        if filename.lower().endswith('.html'):
            file_path = os.path.join(folder_path, filename)

            with open(file_path, 'r', encoding='utf-8') as file:
                content = file.read()

            new_content = remove_double_quotes_from_meta(content)

            with open(file_path, 'w', encoding='utf-8') as file:
                file.write(new_content)

# Calea către folderul cu fișierele HTML
folder_path = r'c:\Folder-Oana\extracted\translated'

# Procesarea fișierelor
process_html_files(folder_path)
```

**Comment by mrabarnett** [comment]
My pattern worked for me.

I also tried both patterns in EditPad Pro and got the same result.

**Comment by mrabarnett** [comment]
I've just released regex 2023.12.25, so the original pattern should now work.

It also now supports `\R`.

**Comment by me-suzy** [comment]
should I update the library, or run the code to see the changes?

**Comment by mrabarnett** [comment]
It's a new release. You'll need to update it. On Windows it's recommended to use the Python Launcher, so `py -m pip install --upgrade regex`.
