### ISSUE TITLE
Build failure with stricter C compilers on x86

### ISSUE THREAD

**Issue by thesamesam** [mrabarnett/mrab-regex#521]
GCC 14 will make `-Wincompatible-pointer-types` as well as some other serious warnings errors by default. See https://wiki.gentoo.org/wiki/Modern_C_porting#What_changed.3F for the full list.

Originally reported downstream in Gentoo at https://bugs.gentoo.org/924136.

```
2024-02-09 09:05:01,712 root INFO creating /var/tmp/portage/dev-python/regex-2023.12.25/work/regex-2023.12.25-pypy3/build/temp.linux-i686-pypy310/regex_3
2024-02-09 09:05:01,713 root INFO i686-pc-linux-gnu-gcc -O2 -march=i686 -pipe -pipe -frecord-gcc-switches -fno-diagnostics-color -fmessage-length=0 -UNDEBUG -fPIC -I/usr/include/pypy3.10 -c regex_3/_regex.c -o /var/tmp/portage/dev-python/regex-2023.12.25/work/regex-2023.12.25-pypy3/build/temp.linux-i686-pypy310/regex_3/_regex.o
regex_3/_regex.c: In function ‘build_unicode_value’:
regex_3/_regex.c:9413:16: error: assignment to ‘Py_UCS4 *’ {aka ‘unsigned int *’} from incompatible pointer type ‘Py_UNICODE *’ {aka ‘long int *’} [-Wincompatible-pointer-types]
 9413 |         to_ptr = codepoints;
      |                ^
regex_3/_regex.c:9428:16: error: assignment to ‘Py_UCS4 *’ {aka ‘unsigned int *’} from incompatible pointer type ‘Py_UNICODE *’ {aka ‘long int *’} [-Wincompatible-pointer-types]
 9428 |         to_ptr = codepoints;
      |                ^
regex_3/_regex.c:9444:16: error: assignment to ‘Py_UCS4 *’ {aka ‘unsigned int *’} from incompatible pointer type ‘Py_UNICODE *’ {aka ‘long int *’} [-Wincompatible-pointer-types]
 9444 |         to_ptr = codepoints;
      |                ^
regex_3/_regex.c:9460:16: error: assignment to ‘Py_UCS4 *’ {aka ‘unsigned int *’} from incompatible pointer type ‘Py_UNICODE *’ {aka ‘long int *’} [-Wincompatible-pointer-types]
 9460 |         to_ptr = codepoints;
      |                ^
error: command '/usr/bin/i686-pc-linux-gnu-gcc' failed with exit code 1
 * ERROR: dev-python/regex-2023.12.25::gentoo failed (compile phase):
 *   Wheel build failed
```

**Comment by mrabarnett** [comment]
Are you compiling for PyPy?

PyPy stores strings as UTF-8, but this module has never supported variable-byte encodings. Only ASCII-range strings will work properly.

This is mentioned in the main page.

I really need to strip out that code and make it raise a compile-time error if `PYPY_VERSION` is defined.

**Comment by thesamesam** [comment]
Yeah, this is from a PyPy build (sorry, I'd missed that myself, or I would've said it prominently). Thanks.

**Comment by mgorny** [comment]
> PyPy stores strings as UTF-8, but this module has never supported variable-byte encodings. Only ASCII-range strings will work properly.

I'm sorry but are you sure about that? According to PyPy upstream, everything exposed via the C API should be recoded to UCS. From a quick testing, it seems that matching using non-ASCII strings works as expected:

```python
>>>> import regex
>>>> r=regex.compile(r"ąćęł\s*", regex.UNICODE)
>>>> r.match("ąćęł  ")
<regex.Match object; span=(0, 6), match='ąćęł  '>
>>>> r=regex.compile(r"\w*", regex.UNICODE)
>>>> r.match("ąćęł")
<regex.Match object; span=(0, 4), match='ąćęł'>
```

I've also been able to compile it successfully and run these examples after removing all code conditional to `PYPY_VERSION`.

**Comment by mrabarnett** [comment]
I'm not sure about the current state of PyPy as I haven't been following it, but there was a time when it didn't work properly.

Is there a list somewhere of which functions it supports?

**Comment by mgorny** [comment]
I'm not aware of an exact list but PyPy aims to support everything that's in public CPython API, and if anything's missing, they are generally helpful and willing to implement it. The [Differences between PyPy and CPython](https://doc.pypy.org/en/latest/cpython_differences.html) doc may be relevant though.

CC @mattip @cfbolz
