### ISSUE TITLE
Request for Detailed Documentation

### ISSUE THREAD

**Issue by s-jamshidian** [mrabarnett/mrab-regex#523]
Dear Maintainer,

I am currently utilizing the `regex` module in Python and find it to be an invaluable tool. I would like to express my appreciation for the effort you have invested in developing and maintaining this module.

While the **README** page has been a useful reference, I am interested in knowing if there exists a more comprehensive, dedicated documentation for the `regex` module. If such a resource is available, could you provide me with the link?

Access to detailed documentation would significantly aid myself and other users in fully understanding the capabilities of the `regex` module and utilizing it to its full potential.

Thank you for your time and consideration.

**Comment by mrabarnett** [comment]
There's no more documenation.

**Comment by cameron-emburse** [comment]
More documentation would certainly be useful.
