### ISSUE TITLE
Fuzzy match with multiple words and different error possibility

### ISSUE THREAD

**Issue by SantoSimone** [mrabarnett/mrab-regex#524]
I have a list of strings which I would like to find in a text. These strings could be single or multiple words.

I would also like to match corrupted texts up to a certain amount of errors, but would like to specify how much error for each string.

I would also like to match any string only if there are word boundaries around it, i.e. `\b{string}\b`

<br/>

I will give an example:

```
list_of_strings = ['base', 'two words']
errors = [1, 2]
good_text = 'I am trying to find base with at most 1 error, while two words with at most 2 errors'
corrupted_but_good_text = 'I am trying to find baXse with at most 1 error, while two words with at most 2 errors'
bad_text = 'I am trying to find aaaa with at most 1 error, while bbb words with at most 2 errors'
```

I tried to construct the pattern in the following way (and some variations of it):

```
pattern = r'\b('
for s, err in zip(list_of_strings, errors):
    pattern += f'({s})' + '{e<=' + f'{err}' + '}|' 

pattern = pattern[:-1] # remove last pipe
pattern += r')\b'
reg = regex.compile(pattern, flags=regex.IGNORECASE | regex.VERSION1)
```

Which results in: `pattern = '\b((base){e<=1}|(two words){e<=2})\b'`

Note that I use `(base){e<=1}` because if I write `base{e<=1}` (without parenthesis) it does not match the `corrupted_but_good_text`
 
But running `reg.findall('Theres only base')`, the result is:

`(' base', ' base', '')`

I am not sure how I should interpret this and I think I am missing some crucial parts of the matching functionality / pattern definition.

Anyway, I would like the pattern to match `base` OR `two words` (OR any other item in `list_of_strings`) with (possibly) different error tolerance for each item, is it possible?

**Comment by mrabarnett** [comment]
Firstly, if you write, say, `base*`, the `*` will apply to only the preceding `e`. `+` and `?` behave the same way, and so do `{2}` and `{2,4}`.

`base{e<=1}` is just the same.

Secondly, `(base)` is a capture group, so `(base){e<=1}` is a capture group with fuzzy matching.

If you don't want the capturing, use a non-capture group, `(?:base)`, or `(?:base){e<=1}`.

Thirdly, `.findall` returns a list of either the entire match if there are no capture groups, or the captured part if there is 1 capture group, or tuples of strings if there are 2 or more capture groups.

Your pattern had 3 capture groups, therefore `.findall` returned a list of 3-tuples.

Fourthly, I recommend you add the `(?e)` flag to the pattern. This will 'tweak' the fuzzy match, checking whether it shorten the matches without affecting the errors, and this will often trim their ends, resulting in a 'better' match.

So, the pattern I'd suggest is `r'(?e)\b(?:(?:base){e<=1}|(?:two words){e<=2})\b'`.

Here's a comparison:

```
>>> regex.findall(r'\b(?:(?:base){e<=1}|(?:two words){e<=2})\b', 'Theres only base')
[' base']
>>> regex.findall(r'(?e)\b(?:(?:base){e<=1}|(?:two words){e<=2})\b', 'Theres only base')
['base']
```
