### ISSUE TITLE
Difference in compiled vs. non-compiled pattern search

### ISSUE THREAD

**Issue by krdav** [mrabarnett/mrab-regex#528]
Expected observation when pattern is not compiled:
```
non_compiled_search = regex.search(
                r"(?P<discard_1>TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG){e<1}(?P<umi_1>.{8,16})(?P<discard_2>CCACTCCAAAAACCTGACCTG){e<=1}",
                "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGCATCATTTGAAGGCCACTCCAAAAACCTGACCTGGTCGTGACGTCTGA",
                regex.BESTMATCH,
            )

non_compiled_search
<regex.Match object; span=(0, 68), match='TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGCATCATTTGAAGGCCACTCCAAAAACCTGACCTG'>
```

Unexpected observation when the pattern _is_ compiled:
```
compiled_pattern = regex.compile(r"(?P<discard_1>TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG){e<1}(?P<umi_1>.{8,16})(?P<discard_2>CCACTCCAAAAACCTGACCTG){e<=1}")
compiled_search = compiled_pattern.search(
                "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGGCATCATTTGAAGGCCACTCCAAAAACCTGACCTGGTCGTGACGTCTGA",
                regex.BESTMATCH,
            )

compiled_search
None
```

Am I doing anything wrong here? Wouldn't the expected behavior be the same for both compiled and non-compiled pattern searches?

**Comment by 5j9** [comment]
You should pass the `regex.BESTMATCH` flag to `regex.compile` function as the second argument. When calling `.search` method on `compiled_pattern`, the second argument is `pos` (start position).

**Comment by mrabarnett** [comment]
@5j9 is correct.

Here's `regex`:

```
The `search` function:

    search(pattern, string, flags=0, pos=None, endpos=None, partial=False, concurrent=None, timeout=None, ignore_unused=False, **kwargs)

The `search` method:

    search(string, pos=None, endpos=None, concurrent=None, timeout=None)
```

Why is it like that?

Well, here's `re`:

```
The `search` function:

    search(pattern, string, flags=0)

The `search` method:

    search(string, pos=0, endpos=9223372036854775807)
```

And `regex` is intended to be backwards-compatible with `re`.

**Comment by krdav** [comment]
Excellent! Thanks for the help.

I should have just read the function vs. method documentation. I guess strict backwards compatibility with `re` makes it impossible to do a type check on the `pos` argument passed to the search method.
