### ISSUE TITLE
hangs with fuzzy and optionals

### ISSUE THREAD

**Issue by dragoncoder047** [mrabarnett/mrab-regex#530]
```python
Python 3.12.3 (main, Apr 15 2024, 14:47:09) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import regex
>>> regex.__version__
'2.5.144'
>>> pat = r"^(\b(does){e<=5}\b)((?P<x>\s+zzz\s+\b\L<x>\b){e<=9})?$"
>>> tgt = "don't"
>>> kwargs = {"x": ["foo", "bar"]}
>>> print(regex.match(pat, tgt, flags=regex.BESTMATCH | regex.IGNORECASE, **kwargs))
^CKeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/current/lib/python3.12/site-packages/regex/regex.py", line 254, in match
    return pat.match(string, pos, endpos, concurrent, partial, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <method 'match' of '_regex.Pattern' objects> returned a result with an exception set
>>>
```

**Comment by mrabarnett** [comment]
It's not hanging, it'll finish eventually. It's just an example of catastrophic backtracking.

The error printed when Ctrl+C is pressed does show a bug, though, which is fixed in regex 2024.5.15.

**Comment by dragoncoder047** [comment]
Where is the pathological backtracking part? Is that caused by the fuzzy matching?

**Comment by 5j9** [comment]
I'm not very familiar with fuzzy matching but the logic looks expensive and adding a free-to-backtrack quantifier *inside* a fuzzy matching group will probably exponentially increase the cost. Try replacing all `\s+` with `\s++`.

**Comment by mrabarnett** [comment]
The pattern starts with a subpattern that could have up to 5 errors, and then follows it with an optional subpattern that contains 2 repetitions and could have up to 9 errors.

The ways that it could match soon add up, and it has to try all of them because you're asking for the best one.

**Comment by dragoncoder047** [comment]
OK, that explains it. I revised the (exemplary) regex to:

```python
r"^(\b(does){e<=5}\b)((?P<x>\s+(zzz){e<=1}\s+(\b\L<x>\b){e<=5}))?$"
```

so that the repeats are not inside the fuzzy, and it worked super fast.
