### ISSUE TITLE
Get all subscript matches as a list.

### ISSUE THREAD

**Issue by CabalCrow** [mrabarnett/mrab-regex#532]
I know you can access subscript matches via
```python
m = regex.match(r"(\w)+", "abc")
m.expandf("{1[0]} {1[1]} {1[2]}")
```
Is there way to get all the matches as a list? Something like:
```python
m.group_all(capture_group_index)[subscript_index]
```
Similar question for the start & end methods?

**Comment by mrabarnett** [comment]
Well, there are the `captures`, `starts` and `ends` methods, if that's what you're talking about.

**Comment by CabalCrow** [comment]
Thank you that is exactly what I was looking for!
