### ISSUE TITLE
Release 2024.07.24 cannot be installed

### ISSUE THREAD

**Issue by peov** [mrabarnett/mrab-regex#540]
Hi,

I just noticed that 2024.07.24 was released, because most of my poetry services no longer can be installed.
The release seems broken. I tried poetry cache clears and also went up in a new venv, however I always get the same error:

 - Installing regex (2024.7.24): Failed

  RuntimeError

  Unable to find installation candidates for regex (2024.7.24)

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\installation\chooser.py:74 in choose_for
       70│
       71│             links.append(link)
       72│
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│

Cannot install regex.

Pinning the previous version works, but is kind of tedious to do in all pyproject files. If I am overlooking something here, please enlighten me, thank you :)

**Comment by mrabarnett** [comment]
I use pip, and that works fine on both Windows and Linux.

Why does poetry complain? I have no idea.

**Comment by mrabarnett** [comment]
Have you retried?

It occurred to me that as you reported this issue very soon after the new release was published, it might just be that you were trying to update during the release process, while the wheels were being uploaded.

It can take a few minutes to upload all of them, so, at that time, the particular wheel you wanted might not have been present yet.

**Comment by peov** [comment]
Hi,
So I just tried again and it is sadly still failing for me. First thing I
also did was double check on pypi that the wheel for my machine was already
available, which was the case for about 20 minutes at the time of checking.

Pip (bundled with python 3.12.3) however does not have this issue at the
moment. I therefore think it might be related to my poetry cache and will
report back later.

**Comment by peov** [comment]
Hi,

So I just set up a whole new venv of the project on a different machine that did not run poetry before, and there it now works fine. I there fore close this issue as it is most likely related to my poetry environment, but still weird since I never had this issue before even with stuff that was released literally seconds prior... I might open up an issue with poetry as clearing the cache did not help and the wheel was definietely available.

Thanks and sorry for the disturbane :)
