### ISSUE TITLE
Reverse search with backreference fails to find match

### ISSUE THREAD

**Issue by windymilla** [mrabarnett/mrab-regex#542]
If regex contains a backreference, then searching with the REVERSE flag fails to find a match.
Minimal example:
```
python -c 'import regex; print(regex.search(r"(.)\1", "aabaa"))'
<regex.Match object; span=(0, 2), match='aa'>
```
whereas
```
python -c 'import regex; print(regex.search(r"(.)\1", "aabaa", flags=regex.REVERSE))'
None
```

**Comment by mrabarnett** [comment]
It's not just searching backwards, it's matching backwards.

It needs to capture before it can refer to what it has captured, so when matching forwards it needs to be `r"(.)\1"`, but when matching backwards it needs to be `r"\1(.)"`.

This is also true within lookbehinds.

**Comment by windymilla** [comment]
Thank you.
