### ISSUE TITLE
regex._regex_core.error: bad escape \S (and others) in repl string

### ISSUE THREAD

**Issue by wyattscarpenter** [mrabarnett/mrab-regex#543]
I'm trying to programmatically construct a regular expression string from another string, using regex. That's not important. What's important is I've found if you put `\S`, or `\w`, into the repl parameter, you get an exception. You have to use `\\S` instead. Note that I am using raw strings. Here's an example:

```python3
>>> regex.sub("x", r"\S", "yxy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wyatt\AppData\Local\Programs\Python\Python312\Lib\site-packages\regex\regex.py", line 278, in sub
    return pat.sub(repl, string, count, pos, endpos, concurrent, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyatt\AppData\Local\Programs\Python\Python312\Lib\site-packages\regex\regex.py", line 706, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyatt\AppData\Local\Programs\Python\Python312\Lib\site-packages\regex\_regex_core.py", line 1730, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \S at position 2
>>> regex.sub("x", r"\n", "yxy")
'y\ny'
>>> regex.sub("x", r"\\S", "yxy")
'y\\Sy'
>>> g = regex.sub("x", r"\\S", "yxy") #remember that the strings output to the terminal are not raw, so where they say \\S they mean \S
>>> print(g)
y\Sy
>>>
```

(incidentally, since my actual use-case involves using `\1`, interpreted to be the contents of a match, in the repl, a potential solution like "set a flag so the repl is never interpreted" would not work for me)

**I think the correct behavior would be to allow a literal `\S` in the repl string, which would evaluate to the characters `\S`. However, it is a design decision to be made about what is correct, ultimately. If you choose the other way, I think the error message should explain a little bit more that all escapes in repl strings are also interpreted by regex.**

This is technically a regression (or perhaps a fix, oho!); in some regex version before Sat Oct 29 16:03:51 2022 -0700, which I had installed at that time, my project worked. I don't know which one. (perhaps it was back in one that had a semver version of 1, in which case, good job following semver fastidiously!)

It seems like  `ignore_unused=True` does not help the situation (whatever it's actually supposed to do).

re has a similar behavior

```python3
>>> import re
>>> re.sub("x", r"\S", "yxy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wyatt\AppData\Local\Programs\Python\Python312\Lib\re\__init__.py", line 186, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyatt\AppData\Local\Programs\Python\Python312\Lib\re\__init__.py", line 334, in _compile_template
    return _sre.template(pattern, _parser.parse_template(repl, pattern))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wyatt\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py", line 1075, in parse_template
    raise s.error('bad escape %s' % this, len(this)) from None
re.error: bad escape \S at position 0
>>> re.sub("x", r"\\S", "yxy")
'y\\Sy'
```

By the way: thanks for this great package!

**Comment by facelessuser** [comment]
You could use `subf` which uses `{1}` instead of `\1` for groups. This turns off expectations related to `\`:

```py
>>> regex.subf('x', r'\s', 'x')
'\\s'
```

Of course, when you need to use braces, you must escape them `{{`/ `}}`.

**Comment by mrabarnett** [comment]
The replacement can include `\g<1>` as an alternative to `\1` or `\g<name>` for a named group, so it already needs to support escape sequences.

I take the position that if it looks like an escape sequence, it's either a current one or a potential one, i.e. reserved for future use.

Historically, Python treated undefined escape sequences such as `\p` as a literal, but that was changed in later versions.

`regex` supports multiple versions of Python and has lagged behind somewhat and retained the old behaviour so as not to break old code, but that won't be the case forever.
