### ISSUE TITLE
Allow `overlapped` to return matching strings overlapping from the start.

### ISSUE THREAD

**Issue by fcolecumberri** [mrabarnett/mrab-regex#545]
I know this has been proposed in several issues (so it's clear people might find it useful) and you have rejected the idea because it may lead into a combinatorial potentially infinite grow of matches.

However that hazard could be reduced if you changing `overlapped` from `bool` → `bool|int` where if `bool`, it keeps the current behavior, but if `int`, allow overlapping from the start, up to the `overlapped` value.

**Comment by mrabarnett** [comment]
What you mean by "up to the `overlapped` value"?

I'm not planning adding any more features because the existing code is already complicated enough.

**Comment by fcolecumberri** [comment]
I mean if `overlapped=10` once there are 10 matches, return those 10. There might be more, but by forcing the user to put a limit, it can not go to infinity.
