### ISSUE TITLE
Unexpected match in regex

### ISSUE THREAD

**Issue by thomas-strafrac** [mrabarnett/mrab-regex#548]
Hello ! 
Recently I was having fun doing regex on Indian and Arabic characters and I came across a behavior that I find suspicious. Here's an example of a sentence I use  `परत‍िन‍िधिमंडल` If we look at the hexadecimal decomposition of my sentence, we can see that it contains ZWJ (Zero-width joiner) characters -> U+200D: 

```
प -> U+092A
र -> U+0930
त -> U+0924
‍ -> U+200D
ि -> U+093F
न -> U+0928
‍ -> U+200D
ि -> U+093F
ध -> U+0927
ि -> U+093F
म -> U+092E
ं -> U+0902
ड -> U+0921
ल -> U+0932
```

If I refer to your documentation, it says : 

```
    \w              Matches any alphanumeric character; equivalent to
                    [a-zA-Z0-9_] when matching a bytestring or a Unicode string
                    with the ASCII flag, or the whole range of Unicode
                    alphanumeric characters (letters plus digits plus
                    underscore) when matching a Unicode string. With LOCALE, it
                    will match the set [0-9_] plus characters defined as
                    letters for the current locale.
```

If I now look at the properties of the character \u200D we can read there (https://www.fileformat.info/info/unicode/char/200d/index.htm) : 
```
Character.isDigit()  => No
Character.isLetter()  => No
And it's obviously not an underscore
```

So logically, if I make a regex based on just \w I shouldn't match my character.
Except :

```
print(regex.match(r'([\w]+)', '\u200D'))
<regex.Match object; span=(0, 1), match='\u200d'>
```
We've got a match when we shouldn't have 😢

Here is a comparison with the same regex in python using `re` :

```
>>> print(re.match(r'(\w)', '\u200D'))
None
>>> print(regex.match(r'(\w)', '\u200D'))
<regex.Match object; span=(0, 1), match='\u200d'>
```

**Comment by mrabarnett** [comment]
That's just a simplified definition.

In ASCII that would be a complete, but in Unicode it's a lot more complicated:

`[\p{alpha}\p{gc=Mark}\p{digit}\p{gc=Connector_Punctuation}\p{Join_Control}]`

The fuller definition is given here:

https://www.unicode.org/reports/tr18/#Compatibility_Properties
